version:"3"

services:
  redis:
    image:redis

  db:
    image: postgres:9.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    ports:
      - 5000:80

  worker:
    image: worker-app
    link:
      - db
      - redis

  result:
    image: result-app
    port:
      - 5001:80
    

  

